# font
# font_family JetBrainsMono Nerd Font
font_family FiraCode Nerd Font
# font_family Maple Mono
font_size 14
disable_ligatures never

## color
include theme.conf

# cursor
cursor none
shell_integration no-cursor
cursor_shape block
cursor_text_color background

# mouse
mouse_hide_wait 3.0

# bell
enable_audio_bell no

background_opacity 0.9
