# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 1, 3, 4 ]

[opener]
edit = [
  { run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = 'code "%*"',    orphan = true, desc = "code",         for = "windows" },
  { run = 'code -w "%*"', block = true,  desc = "code (block)", for = "windows" },
]
open = [
  { run = 'xdg-open "$@"',                desc = "Open", for = "linux" },
  { run = 'open "$@"',                    desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$0")"',            desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"',                          desc = "Reveal", for = "macos" },
  { run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'unar "$1"', orphan = true, desc = "Extract here", for = "unix" },
  { run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
  { run = 'mpv --force-window "%1"', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
image = [
  { run = 'nomacs "$@"',  desc = "ImageOpen", for = "linux" },
]

[open]
rules = [
  { name = "*/", use = [ "edit", "open", "reveal" ] },

  { mime = "text/*",          use = [ "edit", "reveal" ] },
  { mime = "image/*",         use = [ "image", "reveal" ] },
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  { mime = "inode/x-empty",   use = [ "edit", "reveal" ] },

  { mime = "application/zip",             use = ["extract"] },
  { mime = "application/tar.xz",          use = ["extract"] },
  { mime = "application/gzip",            use = ["extract"] },
  { mime = "application/x-bzip",          use = ["extract"] },
  { mime = "application/x-bzip2",         use = ["extract"] },
  { mime = "application/x-tar",           use = ["extract"] },
  { mime = "application/x-7z-compressed", use = ["extract"] },
  { mime = "application/x-rar",           use = ["extract"] },

  { mime = "application/json", use = [ "edit", "reveal" ] },
  { mime = "*/javascript",     use = [ "edit", "reveal" ] },

  { mime = "pdf",  use = [ "open", "reveal" ] },

  { mime = "*", use = [ "open", "reveal" ] },
]
